import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebars: SidebarsConfig = {
  docs: [
    "README",
    {
      type: "category",
      label: "Get started",
      items: ["getting-started", "deployment", "configuration", "release-status"]
    },
    {
      type: "category",
      label: "Use the Bridge",
      items: [
        "architecture",
        "commands",
        "thread-binding",
        "admission",
        "delivery",
        "approval-routing",
        "message-archive"
      ]
    },
    {
      type: "category",
      label: "Channels",
      items: ["qq-adapter", "whatsapp-adapter"]
    },
    {
      type: "category",
      label: "Operations",
      items: ["operations", "migrations", "limits-and-roadmap"]
    },
    {
      type: "category",
      label: "Developers and reference",
      collapsed: true,
      items: [
        "development",
        {
          type: "category",
          label: "Architecture decisions",
          items: [{ type: "autogenerated", dirName: "adr" }]
        },
        { type: "link", label: "Source repository", href: "https://github.com/mwe-support/codex-channel-bridge" }
      ]
    },
    {
      type: "category",
      label: "Release and CI",
      collapsed: true,
      items: [
        "release",
        {
          type: "category",
          label: "Acceptance evidence",
          items: [{ type: "autogenerated", dirName: "acceptance" }]
        }
      ]
    }
  ]
};

export default sidebars;
